if SERVER then return end

AddCSLuaFile()

print("Loading [LFSimfphys] Star Fox Subtitles file...")

-- SF_SUBTITLES["AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

SF_SUBTITLES = {}

    // Wolf (64)
SF_SUBTITLES["cpthazama/starfox/vo/wolf/WollfCant let you do that.mp3"] = "Can't let you do that, Star Fox."
SF_SUBTITLES["cpthazama/starfox/vo/wolf/WolfPlaytimes over.mp3"] = "Playtime is over, Star Fox."
SF_SUBTITLES["cpthazama/starfox/vo/wolf/Wolfgoing down.mp3"] = "You're in my sights, you're going down!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf/Wolfis that all.mp3"] = "What? Is that all you got?"
SF_SUBTITLES["cpthazama/starfox/vo/wolf/Wolfno way.mp3"] = "No way?! I don't believe it!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf/Wolfwhat the heck.mp3"] = "What the heck?!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf/Wolfyoull be seeing your dad.mp3"] = "You'll be seeing your dad soon, Fox."
SF_SUBTITLES["cpthazama/starfox/vo/wolf/Wolfyoure good im better.mp3"] = "You're good, but I'm better!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf/Wolfyoure not so tough.mp3"] = "You're not so tough!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf/WollfDont get too cocky.mp3"] = "Don't get too cocky, Star Fox."
SF_SUBTITLES["cpthazama/starfox/vo/wolf/WollfI cant lose.mp3"] = "I can't lose!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf/Wollflooks like we win.mp3"] = "Looks like we win today, Star Fox."

    // Wolf (Zero)
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/GO.wav"] = "Go!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/bested_by_a_fox.wav"] = "Bested by a fox?! Impossible!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/come_on.wav"] = "Come on!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/even_trying.wav"] = "Are you even trying?"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/father_put_up_more_fight.wav"] = "What's wrong? Your father put up more of a fight."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/grown_tired.wav"] = "I've grown tired of this!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/hunt_you_down.wav"] = "Wherever you go, I will hunt you down!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/i_cant_lose.wav"] = "I- can't lose!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/i_have_you_in_my_sights.wav"] = "I have you in my sights, you've no escape!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/im_coming_for_you.wav"] = "I'm coming for you, Star Fox."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/im_impressed.wav"] = "I'm impressed. I haven't had this much fun since I fought your father."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/laugh.wav"] = "HYAHAHAHAHAAAA!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/lightning_blaster.wav"] = "Lightning Blaster!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/lightning_tornado.wav"] = "Lightning Tornado!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/not_good_enough.wav"] = "You're good, but not good enough!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/not_so_tough.wav"] = "You're not so tough!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/orbital_wolf.wav"] = "Orbital Wolf!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/pathetic.wav"] = "Pathetic."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/playtime_is_over.wav"] = "Playtime is over, Star Fox."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/shadow_edge.wav"] = "Shadow Edge!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/so_clever.wav"] = "You think you're so clever."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/take_this.wav"] = "Take this!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/that_tickled.wav"] = "That almost tickled!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/thats_as_far_as_you_go.wav"] = "That's as far as you go, Star Fox."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/the_best_you_can_do.wav"] = "Is that the best you can do?"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/too_easy.wav"] = "Too easy."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/too_slow.wav"] = "Too slow!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/what.wav"] = "What?!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/whats_wrong.wav"] = "What's wrong? Is that all you've got?"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_zero/youll_see_father_soon.wav"] = "You'll be seeing your father soon!"

    // Wolf (Assault)
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/accept_the_truth.wav"] = "That's the truth of it, accept it Fox."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/aint_your_father.wav"] = "You ain't your father after all."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/amaetures.wav"] = "Don't get upety you amaetures!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/cant_believe_beat.wav"] = "Can't believe I'd get beat."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/dance_partner.wav"] = "It's been a long time Fox. C'mon, I'll be your dance partner."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/death1.wav"] = "Ugh. Guess I'm not as sharp as I used to be..."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/death2.wav"] = "Agghh."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/done_already.wav"] = "What's the problem, you done already?"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/dont_hesitate.wav"] = "Don't hesitate Fox, you've gotta do it!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/dropped_in_unannounced.wav"] = "You're the one who dropped in unannounced, and if anyones gonna tan your hide it's gonna be me."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/aparoid_comment1.wav"] = "They look like sturdy little monsters don't they?"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/aparoid_comment2.wav"] = "These things again? They ain't worth the time!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/aparoid_comment3.wav"] = "Looks like they got a thing for us."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/aparoid_comment4.wav"] = "C'mon you stinking bugs!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/easy_to_say.wav"] = "That's easy to say after all you've done."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/eating_blasterfire.wav"] = "Agh! I'm eating blaster fire!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/enter_ship.wav"] = "That's mine!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/fools.wav"] = "You fools!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/friendlyfire1.wav"] = "What are you aiming at?!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/friendlyfire2.wav"] = "What are you doing to my darling Wolfen?"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/friendlyfire3.wav"] = "Point that thing at me and you better be ready to die pup!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/go_down.wav"] = "Go down Fox!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/got_questions.wav"] = "You got questions? You're gonna have to out-fly me first."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/gotten_soft.wav"] = "You've gotten soft pup."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/idiots_up_to.wav"] = "What are you idiots up to now?"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/just_act.wav"] = "Let me give you one piece of advice, don't hesitate. When the time comes, just act."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/leon.wav"] = "Leon."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/lets_do_this.wav"] = "Let's do this."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/lockon_comment1.wav"] = "One of these scum have a lock on me."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/lockon_comment2.wav"] = "Curses! Someone's locked on me!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/lockon_comment3.wav"] = "I can't shake 'em!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/lockon_comment4.wav"] = "Curses! Got one on my tail, I've gotta shake 'em!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/my_turf.wav"] = "You're on my turf now, watch your step."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/not_done_yet.wav"] = "We're not done yet!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/not_saving_you.wav"] = "I thought I told you? I didn't come here to save you."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/pain1.wav"] = "Urgh!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/pain2.wav"] = "Don't mess with me Fox!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/pain3.wav"] = "Now you've done it!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/pain4.wav"] = "You impudent!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/pain5.wav"] = "I've taken heavy fire, but I'm just getting started!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/pain6.wav"] = "Argh! Can't seem to pull it together."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/pain7.wav"] = "Nrgh! I'm not used to being the one taking damage."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/panther.wav"] = "Panther."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/panther_leon_Letsgo.wav"] = "Panther. Leon. Let's go!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/pay_attention.wav"] = "Pay attention."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/pigma_apology.wav"] = "Pigma? Don't know anything about Pigma, but there is one thing. I'm owed an apology, and I will have it!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/pitiful_sight.wav"] = "You're a pitiful sight pup."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/settle_this.wav"] = "Enough small talk, let's settle this Fox."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/space_on_my_wing.wav"] = "Hmph. So how long you plan on taking up space on my wing?"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/spawn.wav"] = "I'll get it done!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/spot_enemy1.wav"] = "It's the enemy Fox!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/star_wolf_will_take_you_down.wav"] = "Remember this Fox, Star Wolf will take you down one day!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/stupid_look.wav"] = "Wipe that stupid look off your mug!"
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/talk_too_much.wav"] = "You talk too much."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/thats_enough.wav"] = "That's enough for now Fox."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/thats_the_end.wav"] = "That's the end of it."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/threw_pigma_out.wav"] = "Pigma's no longer part of Star Wolf, and if he'd shown his filthy hide here my men would have driven him out."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/you_look_raged.wav"] = "You all right? You look ragged."
SF_SUBTITLES["cpthazama/starfox/vo/wolf_assault/you_survived.wav"] = "I guess you survived, huh?"

    // Panther (Assault)
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/dazzle_aerial_moves.wav"] = "I've gotta stop dazzling everyone with my aerial moves."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/death1.wav"] = "How could this be?! I've been..."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/favorite_cafe.wav"] = "Oh no, one of my favorite cafes got totaled."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/first_class_meal.wav"] = "When this is all done, I want a first-class meal."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/aparoid_comment1.wav"] = "You really enjoy shooting these creeps, huh?"
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/good_as_i_heard.wav"] = "Oh wow, you're nearly as good as I heard."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/grand_finale.wav"] = "Looks like we're getting close to the grand finale hun."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/introduction.wav"] = "Allow me to introduce myself, I am Panther, and all who see my rose meet death. *Growl*"
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/make_me_mad.wav"] = "Make me mad and your life is as good as gone!"
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/no_time_for_pleas.wav"] = "This isn't the time for pleasantries is it?"
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/okay_fine.wav"] = "Okay, fine."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/pain1.wav"] = "Not bad."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/protect_krystal.wav"] = "Riight. Don't worry Krystal, I'll protect you from hear-on-in."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/quiet_bird.wav"] = "Quiet, bird."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/resist_this_beauty.wav"] = "How can I resist this beauty? I believe the comm record will point you towards Fichina."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/ride_my_wing_krystal.wav"] = "You wanna ride on my wing, Krystal?"
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/see_krystal_again.wav"] = "I'd like to see you again once this is all done."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/stole_prey.wav"] = "Hmph, stealing someone's prey is rude you know?"
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/the_lovely_krystal.wav"] = "Ah, the lovely Krystal. Words do you no justice. I am Panther Caroso, here's to us. Ouwe."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/where_you_looking.wav"] = "Where are you looking?!"
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/whistle.wav"] = "*Whistle*"
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/you_looking_to_die.wav"] = "You lookin' to die, runt?"
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/youre_doing_okay.wav"] = "You're doing okay, I'd expect nothing less from my rival."
SF_SUBTITLES["cpthazama/starfox/vo/panther_assault/youre_looking_good.wav"] = "You're looking good big guy."

    // Leon (Assault)
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/cocky_as_ever.wav"] = "Hey, cocky as ever aye bird brain?"
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/cook_torment.wav"] = "Heheh, I think I'll torment you a bit before I cook you!"
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/death1.wav"] = "Me?! Me!"
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/all_you_got.wav"] = "So this is all you've got pup?"
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/aparoid_comment1.wav"] = "Ugly bugs. It's no fun fighting unshakable enemies."
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/aparoid_comment2.wav"] = "This is getting on my nerves, you're my prey!"
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/day_to_fight_you.wav"] = "Heh. I'm looking forward to the day I can fight you."
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/end_up_as_target.wav"] = "Go ahead and blunder, and you'll end up as a target!"
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/not_showing_weakness.wav"] = "Heh. Doing your best not to show any weak points aye?"
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/pain1.wav"] = "Tch."
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/say_the_wor.wav"] = "If you fools really want to die, just say-the-word."
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/so_easy.wav"] = "Hmph. That was so easy it was almost boring."
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/steal_prey.wav"] = "What are you doing? That was mine!"
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/surprised_you_got_far.wav"] = "Hmmm I'm surprised you fools have managed to get this far."
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/think_i_am.wav"] = "Who do you think I am?!"
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/too_weak.wav"] = "Weak! Much too weak!"
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/wise_guy.wav"] = "So you're a wise guy, huh?"
SF_SUBTITLES["cpthazama/starfox/vo/leon_assault/youre_in_the_way.wav"] = "You're in the way rookie!"

print("Successfully Loaded [LFSimfphys] Star Fox Subtitles AI file!")